#!/bin/sh
# 用途: RTC 时钟: 让系统时间在重启后仍然正确 (RTC 里存的是 UTC)

case $1 in
start)
	if [ "$(hwclock | grep "1969")" ]; then
		echo "RTC time calibration"
		date -s 2024-01-01
		hwclock -w
	else
		echo "RTC does not require time calibration"
	fi
	;;
*)
	exit 1
	;;
esac
